name: .NET Core

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.102
    - name: Setup nodejs
      uses: actions/setup-node@v1
    - name: Yarn
      working-directory: ./src/BlazorWebView.JS/upstream/aspnetcore/web.js
      run: yarn
    - name: Build BlazorWebView.JS
      working-directory: ./src/BlazorWebView.JS/
      run: dotnet build --configuration Release
    - name: Build BlazorWebView
      working-directory: ./src/BlazorWebView/
      run: dotnet build --configuration Release