name: .NET Core

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.102
    - name: Setup nodejs
      uses: actions/setup-node@v1
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.0
    - name: Yarn
      working-directory: ./src/BlazorWebView.JS/upstream/aspnetcore/web.js
      run: yarn
    - name: Build BlazorWebView.JS
      working-directory: ./src/BlazorWebView.JS/
      run: dotnet build --configuration Release
    - name: Build BlazorWebView
      working-directory: ./src/BlazorWebView/
      run: dotnet build --configuration Release
    - name: Pack BlazorWebView
      working-directory: ./src/BlazorWebView/
      run: dotnet pack --configuration Release
    - name: Push BlazorWebView nuget package
      working-directory: ./src/BlazorWebView/
      run: dotnet nuget push **/*.nupkg --skip-duplicate --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
    - name: BlazorWebView.Native configure32
      working-directory: ./build/
      run: ./native.cmd
    - name: Build BlazorWebView.Wpf
      working-directory: ./src/BlazorWebView.Wpf/
      run: dotnet build --configuration Release
    - name: Pack BlazorWebView.Wpf
      working-directory: ./src/BlazorWebView.Wpf/
      run: dotnet pack --configuration Release
    - name: Push BlazorWebView.Wpf nuget package
      working-directory: ./src/BlazorWebView.Wpf/
      run: dotnet nuget push **/*.nupkg --skip-duplicate --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
